# Webscraping

In [2]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Downloading soupsieve-2.6-py3-none-any.whl (36 kB)
Installing collected packages: soupsieve, beautifulsoup4
Successfully installed beautifulsoup4-4.12.3 soupsieve-2.6

In [3]:
!pip install requests

Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl.metadata (34 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.6)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp312-cp312-win_amd64.whl (102 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: urllib3, charset-normalizer, certifi, requests
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 requests-2.32.3 urllib3-2.2.3

# Beautifulsoup

In [178]:
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"

response = requests.get(url)

print(response.status_code)

soup=BeautifulSoup(response.text,"lxml")


print(soup.div)

200
<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>Learn</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/how-to-videos">How to</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">Install</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>

# attributes of tags

In [180]:
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/phones"

response = requests.get(url)

print(response.status_code)
# print(reponse.text)

soup=BeautifulSoup(response.text,"lxml")

# tags = soup.div

# print(tags.attrs)

tag = soup.header

atr=tag.attrs
print(atr["role"])
print(atr["class"])

200
banner
['navbar', 'fixed-top', 'navbar-expand-lg', 'navbar-dark', 'navbar-static', 'svg-background']

# Navigable String

In [181]:
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/phones"

response = requests.get(url)

print(response.status_code)
# print(reponse.text)

soup=BeautifulSoup(response.text,"lxml")

# tags =soup.div.p.string
tags =soup.header.div.a.button.span
print(tags.string)
# print(tags.string)
# print(tags.text)

200
Toggle navigation

# find() function
* find only first tag

In [186]:
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"

response = requests.get(url)

print(response.status_code)
# print(reponse.text)

soup=BeautifulSoup(response.text,"lxml")

r=(soup.find("h4",{"class":"price float-end card-title pull-right"}))

print(r.string)

desc =soup.find("p",class_="description")

print(desc.string)

200
$69.99
7" screen, Android

# findall() function that
* give us all tags

In [189]:
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"

response = requests.get(url)

print(response.status_code)


soup=BeautifulSoup(response.text,"lxml")

prices=soup.find_all("h4",class_="price float-end card-title pull-right")

print(f"""Total items {len(prices)}""")

print(f"""Price at index {prices[3].text}""")

for i in prices:
    print(i.text)

200
Total items 21
Price at index $97.99
$69.99
$88.99
$96.99
$97.99
$99.99
$101.99
$102.99
$103.99
$107.99
$121.99
$130.99
$148.99
$172.99
$233.99
$251.99
$320.99
$399.99
$489.99
$537.99
$587.99
$603.99

# find_all with regular expression

In [193]:
import re
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"

response = requests.get(url)

print(response.status_code)

soup=BeautifulSoup(response.text,"lxml")


data1=soup.find_all(string="Lenovo IdeaTab")
print(data1)
print(len(data1))
data=soup.find_all(string=re.compile("iPad"))

print(f"""Total items {len(data)}""")

print(data)

200
['Lenovo IdeaTab']
1
Total items 2
['iPad Mini Reti...', 'Apple iPad Air']

In [194]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# Pandas in scraping

In [202]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

url="https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"

response = requests.get(url)

print(response.status_code)

soup=BeautifulSoup(response.text,"lxml")

names=soup.find_all("a",class_="title")
product_name_list=[]

for i in names:
    name=i.text
    product_name_list.append(name)
    
print(product_name_list)


prices=soup.find_all("h4",class_="price float-end card-title pull-right")
product_price_list=[]

for i in prices:
    price=i.text
    product_price_list.append(price)
    
print(product_price_list)

descriptions=soup.find_all("p",class_="description card-text")
product_description_list=[]

for i in descriptions:
    description=i.text
    product_description_list.append(description)

print(product_description_list)

reviews=soup.find_all("p",class_="review-count float-end")
product_review_list=[]

for i in reviews:
    review=i.text
    product_review_list.append(review)

print(product_review_list)

df=pd.DataFrame({"Product Name":product_name_list,"Product Decriiption":product_description_list,"Product Price":product_price_list,"Product Reviews":product_review_list})
df.to_csv("Product_detail.csv")

200
['Lenovo IdeaTab', 'IdeaTab A3500L', 'Acer Iconia', 'Galaxy Tab 3', 'Iconia B1-730H...', 'Memo Pad HD 7', 'Asus MeMO Pad', 'Amazon Kindle', 'Galaxy Tab 3', 'IdeaTab A8-50', 'MeMO Pad 7', 'IdeaTab A3500-...', 'IdeaTab S5000', 'Galaxy Tab 4', 'Galaxy Tab', 'MeMo PAD FHD 1...', 'Galaxy Note', 'Galaxy Note', 'iPad Mini Reti...', 'Galaxy Note 10...', 'Apple iPad Air']
['$69.99', '$88.99', '$96.99', '$97.99', '$99.99', '$101.99', '$102.99', '$103.99', '$107.99', '$121.99', '$130.99', '$148.99', '$172.99', '$233.99', '$251.99', '$320.99', '$399.99', '$489.99', '$537.99', '$587.99', '$603.99']
['7" screen, Android', 'Black, 7" IPS, Quad-Core 1.2GHz, 8GB, Android 4.2', '7" screen, Android, 16GB', '7", 8GB, Wi-Fi, Android 4.2, White', 'Black, 7", 1.6GHz Dual-Core, 8GB, Android 4.4', 'IPS, Dual-Core 1.2GHz, 8GB, Android 4.3', '7" screen, Android, 8GB', '6" screen, wifi', '7", 8GB, Wi-Fi, Android 4.2, Yellow', 'Blue, 8" IPS, Quad-Core 1.3GHz, 16GB, Android 4.2', 'White, 7", Atom 1.2GHz, 8GB, Android 4.4', 'Blue, 7" IPS, Quad-Core 1.3GHz, 8GB, 3G, Android 4.2', 'Silver, 7" IPS, Quad-Core 1.2Ghz, 16GB, 3G, Android 4.2', 'LTE (SM-T235), Quad-Core 1.2GHz, 8GB, Black', '16GB, White', 'White, 10.1" IPS, 1.6GHz, 2GB, 16GB, Android 4.2', '10.1", 3G, Android 4.0, Garnet Red', '12.2", 32GB, WiFi, Android 4.4, White', 'Wi-Fi + Cellular, 32GB, Silver', '10.1", 32GB, Black', 'Wi-Fi, 64GB, Silver']
['7 reviews', '7 reviews', '7 reviews', '2 reviews', '1 reviews', '10 reviews', '14 reviews', '3 reviews', '14 reviews', '13 reviews', '11 reviews', '9 reviews', '8 reviews', '1 reviews', '14 reviews', '7 reviews', '12 reviews', '9 reviews', '8 reviews', '6 reviews', '7 reviews']

# Tables

In [206]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the Wikipedia page
url = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'

# Send a GET request to fetch the page content
response = requests.get(url)

# Parse the page content with BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Find the first table containing the GDP data
table = soup.find('table', {'class': 'wikitable'})

if table:
    # List to store the extracted data
    all_data = []

    # Manually set the column headers since the table has more than 4 columns
    columns = [
        'Country/Territory', 
        'IMF Forecast (2024)', 'IMF Year', 
        'World Bank Estimate (2023)', 'World Bank Year', 
        'United Nations Estimate (2022)', 'UN Year'
    ]

    # print(f"Columns: {columns}")

    # Extract the table rows (skip the header)
    rows = table.find_all('tr')[1:]

    # Loop through the rows to extract the country GDP data
    for index, row in enumerate(rows):
        cells = row.find_all(['td', 'th'])
        data_row = [cell.get_text(strip=True).replace('\n', ' ') for cell in cells]
        
        # Debugging - Print each row's content
        print(f"Row {index}: {data_row}")
        
        # Ensure only rows with the expected number of columns (7) are processed
        if len(data_row) == 7:
            all_data.append(data_row)
        else:
            print(f"Skipping row {index} due to column mismatch (Expected 7 columns, got {len(data_row)})")
    
    # Debugging - Print all the collected data
    print(f"All data collected: {all_data}")

    # Check if any data was collected
    if all_data:
        # Create a DataFrame using the collected data
        df = pd.DataFrame(all_data, columns=columns)

        # Display the DataFrame
        print(df)

        # Save the data to a CSV file
        df.to_csv('countries_by_gdp.csv', index=True)
        print("Data has been successfully saved to 'countries_by_gdp.csv'")
    else:
        print("No valid data rows were found.")
else:
    print("Table not found on the Wikipedia page.")

Row 0: ['Forecast', 'Year', 'Estimate', 'Year', 'Estimate', 'Year']
Skipping row 0 due to column mismatch (Expected 7 columns, got 6)
Row 1: ['World', '109,529,216', '2024', '105,435,540', '2023', '100,834,796', '2022']
Row 2: ['United States', '28,781,083', '2024', '27,360,935', '2023', '25,744,100', '2022']
Row 3: ['China', '18,532,633', '[n 1]2024', '17,794,782', '[n 3]2023', '17,963,170', '[n 1]2022']
Row 4: ['Germany', '4,591,100', '2024', '4,456,081', '2023', '4,076,923', '2022']
Row 5: ['Japan', '4,110,452', '2024', '4,212,945', '2023', '4,232,173', '2022']
Row 6: ['India', '3,937,011', '2024', '3,549,919', '2023', '3,465,541', '2022']
Row 7: ['United Kingdom', '3,495,261', '2024', '3,340,032', '2023', '3,089,072', '2022']
Row 8: ['France', '3,130,014', '2024', '3,030,904', '2023', '2,775,316', '2022']
Row 9: ['Brazil', '2,331,391', '2024', '2,173,666', '2023', '1,920,095', '2022']
Row 10: ['Italy', '2,328,028', '2024', '2,254,851', '2023', '2,046,952', '2022']
Row 11: ['Canada', '2,242,182', '2024', '2,140,086', '2023', '2,137,939', '2022']
Row 12: ['Russia', '2,056,844', '2024', '2,021,421', '2023', '2,240,422', '2022']
Row 13: ['Mexico', '2,017,025', '2024', '1,788,887', '2023', '1,463,323', '2022']
Row 14: ['Australia', '1,790,348', '2024', '1,723,827', '2023', '1,776,577', '2022']
Row 15: ['South Korea', '1,760,947', '2024', '1,712,793', '2023', '1,673,916', '2022']
Row 16: ['Spain', '1,647,114', '2024', '1,580,695', '2023', '1,415,874', '2022']
Row 17: ['Indonesia', '1,475,690', '2024', '1,371,171', '2023', '1,319,100', '2022']
Row 18: ['Netherlands', '1,142,513', '2024', '1,118,125', '2023', '1,008,027', '2022']
Row 19: ['Turkey', '1,113,561', '2024', '1,108,022', '2023', '907,118', '2022']
Row 20: ['Saudi Arabia', '1,106,015', '2024', '1,067,583', '2023', '1,108,148', '2022']
Row 21: ['Switzerland', '938,458', '2024', '884,940', '2023', '818,426', '2022']
Row 22: ['Poland', '844,623', '2024', '811,229', '2023', '688,125', '2022']
Row 23: ['Taiwan', '802,958', '[n 4]2024', '—', '—']
Skipping row 23 due to column mismatch (Expected 7 columns, got 5)
Row 24: ['Belgium', '655,192', '2024', '632,217', '2023', '582,643', '2022']
Row 25: ['Sweden', '623,048', '2024', '593,268', '2023', '591,188', '2022']
Row 26: ['Argentina', '604,260', '2024', '640,591', '2023', '631,133', '2022']
Row 27: ['Ireland', '564,020', '2024', '545,629', '2023', '532,415', '2022']
Row 28: ['Thailand', '548,890', '2024', '514,945', '2023', '495,340', '2022']
Row 29: ['Austria', '540,887', '2024', '516,034', '2023', '470,302', '2022']
Row 30: ['Israel', '530,664', '2024', '509,902', '2023', '525,002', '2022']
Row 31: ['United Arab Emirates', '527,796', '2024', '504,173', '2023', '507,063', '2022']
Row 32: ['Norway', '526,951', '2024', '485,513', '2023', '579,422', '2022']
Row 33: ['Singapore', '525,228', '2024', '501,428', '2023', '466,788', '2022']
Row 34: ['Philippines', '471,516', '2024', '437,146', '2023', '404,284', '2022']
Row 35: ['Vietnam', '465,814', '2024', '429,717', '2023', '408,802', '2022']
Row 36: ['Iran', '464,181', '2024', '401,505', '2023', '398,047', '2022']
Row 37: ['Bangladesh', '455,162', '2024', '437,415', '2023', '432,677', '2022']
Row 38: ['Malaysia', '445,519', '2024', '399,649', '2023', '406,305', '2022']
Row 39: ['Denmark', '409,989', '2024', '404,199', '2023', '400,167', '2022']
Row 40: ['Hong Kong', '406,775', '[n 5]2024', '382,055', '2023', '359,838', '2022']
Row 41: ['Colombia', '386,076', '2024', '363,540', '2023', '343,939', '2022']
Row 42: ['South Africa', '373,233', '2024', '377,782', '2023', '405,270', '2022']
Row 43: ['Romania', '369,971', '2024', '351,003', '2023', '300,690', '2022']
Row 44: ['Egypt', '347,594', '2024', '395,926', '2023', '409,306', '2022']
Row 45: ['Pakistan', '338,237', '2023', '338,368', '2023', '326,796', '2022']
Row 46: ['Chile', '333,760', '2024', '335,533', '2023', '300,686', '2022']
Row 47: ['Czech Republic', '325,880', '2024', '330,858', '2023', '290,527', '2022']
Row 48: ['Finland', '308,055', '2024', '300,187', '2023', '282,511', '2022']
Row 49: ['Portugal', '298,949', '2024', '287,080', '2023', '254,849', '2022']
Row 50: ['Kazakhstan', '296,740', '2024', '261,421', '2023', '225,496', '2022']
Row 51: ['Peru', '282,458', '2024', '267,603', '2023', '242,631', '2022']
Row 52: ['Algeria', '266,780', '2024', '239,899', '2023', '191,912', '2022']
Row 53: ['Iraq', '265,894', '2024', '250,843', '2023', '264,182', '2022']
Row 54: ['New Zealand', '257,625', '2024', '253,466', '2023', '245,845', '2022']
Row 55: ['Nigeria', '252,738', '2024', '362,815', '2023', '475,058', '2022']
Row 56: ['Greece', '250,276', '2024', '238,206', '2023', '217,285', '2022']
Row 57: ['Qatar', '244,686', '2024', '235,770', '2022', '237,101', '2022']
Row 58: ['Hungary', '223,413', '2024', '212,389', '2023', '177,337', '2022']
Row 59: ['Ethiopia', '205,130', '2024', '163,698', '2023', '118,971', '2022']
Row 60: ['Ukraine', '188,943', '[n 6]2024', '178,757', '[n 6]2023', '160,502', '[n 6]2022']
Row 61: ['Kuwait', '160,397', '2024', '161,772', '2023', '175,363', '2022']
Row 62: ['Morocco', '152,377', '2024', '141,109', '2023', '130,912', '[n 7]2022']
Row 63: ['Cuba', '—', '—', '147,193', '2022']
Skipping row 63 due to column mismatch (Expected 7 columns, got 5)
Row 64: ['Slovakia', '140,808', '2024', '132,794', '2023', '115,304', '2022']
Row 65: ['Dominican Republic', '127,356', '2024', '121,444', '2023', '113,537', '2022']
Row 66: ['Ecuador', '121,592', '2024', '118,845', '2023', '115,049', '2022']
Row 67: ['Puerto Rico', '117,763', '2024', '117,902', '2023', '113,434', '2022']
Row 68: ['Guatemala', '110,035', '2024', '102,050', '2023', '95,003', '2022']
Row 69: ['Oman', '108,927', '2024', '108,192', '2023', '114,666', '2022']
Row 70: ['Bulgaria', '107,933', '2024', '101,584', '2023', '90,213', '2022']
Row 71: ['Kenya', '104,001', '2024', '107,441', '2023', '113,419', '2022']
Row 72: ['Venezuela', '102,328', '2024', '—', '129,313', '2022']
Skipping row 72 due to column mismatch (Expected 7 columns, got 6)
Row 73: ['Uzbekistan', '97,956', '2024', '90,889', '2023', '80,391', '2022']
Row 74: ['Costa Rica', '96,058', '2024', '86,498', '2023', '68,380', '2022']
Row 75: ['Angola', '92,123', '2024', '84,773', '2023', '113,304', '2022']
Row 76: ['Luxembourg', '88,556', '2024', '85,755', '2023', '81,530', '2022']
Row 77: ['Croatia', '88,076', '2024', '82,689', '2023', '71,552', '2022']
Row 78: ['Panama', '87,347', '2024', '83,382', '2023', '76,522', '2022']
Row 79: ['Ivory Coast', '86,911', '2024', '78,789', '2023', '70,018', '2022']
Row 80: ['Uruguay', '82,605', '2024', '77,241', '2023', '71,171', '2022']
Row 81: ['Turkmenistan', '81,896', '2024', '59,887', '2023', '67,009', '2022']
Row 82: ['Serbia', '81,873', '2024', '75,187', '2023', '63,563', '2022']
Row 83: ['Lithuania', '81,170', '2024', '77,836', '2023', '70,878', '2022']
Row 84: ['Tanzania', '79,605', '2024', '79,158', '2023', '73,535', '[n 8]2022']
Row 85: ['Azerbaijan', '78,749', '2024', '72,356', '2023', '78,721', '2022']
Row 86: ['Ghana', '75,244', '2024', '76,370', '2023', '73,766', '2022']
Row 87: ['Sri Lanka', '74,846', '2022', '84,357', '2023', '76,187', '2022']
Row 88: ['DR Congo', '73,761', '2024', '66,383', '2023', '62,551', '2022']
Row 89: ['Slovenia', '72,101', '2024', '68,217', '2023', '59,981', '2022']
Row 90: ['Belarus', '69,048', '2024', '71,857', '2023', '72,873', '2022']
Row 91: ['Myanmar', '68,006', '2024', '64,815', '2023', '65,211', '2022']
Row 92: ['Uganda', '56,310', '2024', '49,273', '2023', '48,243', '2022']
Row 93: ['Tunisia', '54,708', '2024', '48,530', '2023', '46,181', '2022']
Row 94: ['Macau', '54,677', '[n 9]2024', '47,062', '2023', '24,042', '2022']
Row 95: ['Jordan', '53,570', '2024', '50,814', '2023', '47,452', '2022']
Row 96: ['Cameroon', '53,205', '2024', '47,946', '2023', '44,341', '2022']
Row 97: ['Bolivia', '49,334', '2024', '45,850', '2023', '44,008', '2022']
Row 98: ['Libya', '48,221', '2024', '50,492', '2023', '40,537', '2022']
Row 99: ['Bahrain', '46,790', '2024', '43,205', '2023', '44,382', '2022']
Row 100: ['Paraguay', '45,817', '2024', '42,956', '2023', '41,722', '2022']
Row 101: ['Latvia', '45,466', '2024', '43,627', '2023', '40,876', '2022']
Row 102: ['Cambodia', '45,150', '2024', '31,773', '2023', '29,504', '2022']
Row 103: ['Nepal', '44,179', '2024', '40,908', '2023', '39,406', '2022']
Row 104: ['Estonia', '43,486', '2024', '40,745', '2023', '38,049', '2022']
Row 105: ['Honduras', '37,355', '2024', '34,401', '2023', '31,717', '2022']
Row 106: ['Senegal', '35,450', '2024', '31,014', '2023', '27,775', '2022']
Row 107: ['El Salvador', '35,333', '2024', '34,016', '2023', '32,488', '2022']
Row 108: ['Zimbabwe', '34,405', '2024', '26,538', '2023', '26,418', '2022']
Row 109: ['Cyprus', '34,221', '[n 10]2024', '32,230', '[n 10]2023', '29,210', '[n 10]2022']
Row 110: ['Iceland', '33,338', '2024', '31,020', '2023', '28,064', '2022']
Row 111: ['Georgia', '32,865', '[n 11]2024', '30,536', '[n 11]2023', '24,605', '[n 11]2022']
Row 112: ['Papua New Guinea', '31,716', '2024', '30,933', '2022', '31,609', '2022']
Row 113: ['Zambia', '29,872', '2024', '28,163', '2023', '29,136', '2022']
Row 114: ['Bosnia and Herzegovina', '29,078', '2024', '27,055', '2023', '24,473', '2022']
Row 115: ['Trinidad and Tobago', '28,365', '2024', '28,140', '2023', '30,053', '2022']
Row 116: ['Sudan', '26,865', '2024', '109,327', '2023', '36,729', '2022']
Row 117: ['Guinea', '25,447', '2024', '23,612', '2023', '20,846', '2022']
Row 118: ['Albania', '25,431', '2024', '22,978', '2023', '18,916', '2022']
Row 119: ['Armenia', '25,408', '2024', '24,212', '2023', '19,513', '2022']
Row 120: ['Haiti', '24,046', '2024', '19,851', '2023', '18,751', '2022']
Row 121: ['Mozambique', '22,975', '2024', '20,625', '2023', '18,406', '2022']
Row 122: ['Malta', '22,737', '2024', '20,957', '2023', '18,100', '2022']
Row 123: ['Mongolia', '21,943', '2024', '19,872', '2023', '17,146', '2022']
Row 124: ['Burkina Faso', '21,902', '2024', '20,325', '2023', '19,176', '2022']
Row 125: ['Lebanon', '21,780', '2022', '17,937', '2023', '39,303', '2022']
Row 126: ['Mali', '21,662', '2024', '20,905', '2023', '18,827', '2022']
Row 127: ['Botswana', '21,418', '2024', '19,396', '2023', '20,352', '2022']
Row 128: ['Benin', '21,371', '2024', '19,673', '2023', '17,396', '2022']
Row 129: ['Guyana', '21,178', '2024', '16,786', '2023', '14,718', '2022']
Row 130: ['Gabon', '21,013', '2024', '20,516', '2023', '20,132', '2022']
Row 131: ['Jamaica', '20,098', '2024', '19,423', '2023', '17,097', '2022']
Row 132: ['Nicaragua', '18,829', '2024', '17,829', '2023', '15,671', '2022']
Row 133: ['Niger', '18,816', '2024', '16,819', '2023', '15,414', '2022']
Row 134: ['Chad', '18,697', '2024', '13,149', '2023', '16,799', '2022']
Row 135: ['Palestine', '18,602', '[n 12]2023', '17,396', '[n 12]2023', '19,111', '[n 13]2022']
Row 136: ['Moldova', '18,356', '[n 14]2024', '16,539', '[n 14]2023', '14,510', '[n 14]2022']
Row 137: ['Yemen', '16,940', '2024', '—', '11,007', '2022']
Skipping row 137 due to column mismatch (Expected 7 columns, got 6)
Row 138: ['Madagascar', '16,465', '2024', '16,032', '2023', '14,954', '2022']
Row 139: ['Mauritius', '16,359', '2024', '14,397', '2023', '12,898', '2022']
Row 140: ['North Macedonia', '15,873', '2024', '14,761', '2023', '13,711', '2022']
Row 141: ['Brunei', '15,510', '2024', '15,128', '2023', '16,681', '2022']
Row 142: ['Congo', '15,501', '2024', '15,321', '2023', '15,344', '2022']
Row 143: ['Laos', '15,190', '2024', '15,843', '2023', '15,362', '2022']
Row 144: ['North Korea', '—', '—', '15,176', '2022']
Skipping row 144 due to column mismatch (Expected 7 columns, got 5)
Row 145: ['Afghanistan', '14,467', '2022', '14,502', '2022', '14,174', '2022']
Row 146: ['Bahamas', '14,390', '2024', '14,339', '2023', '12,897', '2022']
Row 147: ['Rwanda', '13,701', '2024', '14,098', '2023', '13,312', '2022']
Row 148: ['Kyrgyzstan', '13,599', '2024', '13,988', '2023', '10,930', '2022']
Row 149: ['Tajikistan', '12,953', '2024', '12,061', '2023', '10,492', '2022']
Row 150: ['Somalia', '12,804', '2024', '11,680', '2023', '10,420', '2022']
Row 151: ['Namibia', '12,765', '2024', '12,351', '2023', '12,607', '2022']
Row 152: ['Kosovo', '11,318', '2024', '10,438', '2023', '9,397', '2022']
Row 153: ['Malawi', '11,241', '2024', '14,084', '2023', '12,558', '2022']
Row 154: ['Equatorial Guinea', '10,708', '2024', '12,117', '2023', '11,767', '2022']
Row 155: ['Mauritania', '10,628', '2024', '10,453', '2023', '10,997', '2022']
Row 156: ['Togo', '9,832', '2024', '9,171', '2023', '8,087', '2022']
Row 157: ['New Caledonia', '—', '9,623', '2022', '9,623', '2022']
Skipping row 157 due to column mismatch (Expected 7 columns, got 6)
Row 158: ['Syria', '—', '8,980', '2021', '18,595', '2022']
Skipping row 158 due to column mismatch (Expected 7 columns, got 6)
Row 159: ['Monaco', '—', '8,784', '2022', '8,772', '2022']
Skipping row 159 due to column mismatch (Expected 7 columns, got 6)
Row 160: ['Montenegro', '8,010', '2024', '7,405', '2023', '6,229', '2022']
Row 161: ['Liechtenstein', '—', '7,365', '2022', '7,757', '2022']
Skipping row 161 due to column mismatch (Expected 7 columns, got 6)
Row 162: ['Bermuda', '—', '7,828', '2022', '7,546', '2022']
Skipping row 162 due to column mismatch (Expected 7 columns, got 6)
Row 163: ['Maldives', '7,199', '2024', '6,600', '2023', '6,170', '2022']
Row 164: ['Barbados', '6,863', '2024', '6,394', '2023', '5,699', '2022']
Row 165: ['Cayman Islands', '—', '6,601', '2022', '6,281', '2022']
Skipping row 165 due to column mismatch (Expected 7 columns, got 6)
Row 166: ['South Sudan', '6,517', '2024', '—', '4,616', '2022']
Skipping row 166 due to column mismatch (Expected 7 columns, got 6)
Row 167: ['French Polynesia', '—', '5,815', '2022', '5,814', '2022']
Skipping row 167 due to column mismatch (Expected 7 columns, got 6)
Row 168: ['Fiji', '5,801', '2024', '5,495', '2023', '4,979', '2022']
Row 169: ['Eswatini', '5,085', '2024', '4,598', '2023', '4,326', '2022']
Row 170: ['Liberia', '4,754', '2024', '4,332', '2023', '3,265', '2022']
Row 171: ['Sierra Leone', '4,558', '2024', '3,810', '2023', '3,481', '2022']
Row 172: ['Djibouti', '4,364', '2024', '4,099', '2023', '4,003', '2022']
Row 173: ['Suriname', '4,337', '2024', '3,782', '2023', '3,620', '2022']
Row 174: ['Aruba', '4,069', '2024', '3,545', '2022', '3,544', '2022']
Row 175: ['Andorra', '3,897', '2024', '3,728', '2023', '3,376', '2022']
Row 176: ['Belize', '3,296', '2024', '3,282', '2023', '2,830', '2022']
Row 177: ['Greenland', '—', '3,236', '2021', '2,926', '2022']
Skipping row 177 due to column mismatch (Expected 7 columns, got 6)
Row 178: ['Bhutan', '3,110', '2024', '2,898', '2022', '2,898', '2022']
Row 179: ['Curaçao', '—', '3,074', '2022', '3,075', '2022']
Skipping row 179 due to column mismatch (Expected 7 columns, got 6)
Row 180: ['Burundi', '3,075', '2024', '2,642', '2023', '4,032', '2022']
Row 181: ['Central African Republic', '2,810', '2024', '2,555', '2023', '2,395', '2022']
Row 182: ['Cape Verde', '2,718', '2024', '2,587', '2023', '2,314', '2022']
Row 183: ['Gambia', '2,694', '2024', '2,340', '2023', '2,231', '2022']
Row 184: ['Saint Lucia', '2,582', '2024', '2,520', '2023', '2,165', '2022']
Row 185: ['Lesotho', '2,395', '2024', '2,046', '2023', '2,287', '2022']
Row 186: ['Eritrea', '—', '—', '2,383', '2022']
Skipping row 186 due to column mismatch (Expected 7 columns, got 5)
Row 187: ['Zanzibar', '—', '—', '2,361', '2022']
Skipping row 187 due to column mismatch (Expected 7 columns, got 5)
Row 188: ['Seychelles', '2,203', '2024', '2,141', '2023', '1,994', '2022']
Row 189: ['Guinea-Bissau', '2,151', '2024', '1,966', '2023', '1,574', '2022']
Row 190: ['Antigua and Barbuda', '2,127', '2024', '2,033', '2023', '1,770', '2022']
Row 191: ['San Marino', '2,033', '2024', '1,855', '2021', '1,780', '2022']
Row 192: ['East Timor', '1,992', '2024', '2,243', '2023', '3,204', '2022']
Row 193: ['Solomon Islands', '1,707', '2024', '1,631', '2023', '1,597', '2022']
Row 194: ['Sint Maarten', '—', '1,623', '2023', '1,572', '2022']
Skipping row 194 due to column mismatch (Expected 7 columns, got 6)
Row 195: ['Comoros', '1,422', '2024', '1,352', '2023', '1,246', '2022']
Row 196: ['Grenada', '1,406', '2024', '1,320', '2023', '1,192', '2022']
Row 197: ['Turks and Caicos Islands', '—', '1,402', '2023', '1,138', '2022']
Skipping row 197 due to column mismatch (Expected 7 columns, got 6)
Row 198: ['Vanuatu', '1,289', '2024', '1,126', '2023', '985', '2022']
Row 199: ['Saint Kitts and Nevis', '1,134', '2024', '1,077', '2023', '979', '2022']
Row 200: ['Saint Vincent and the Grenadines', '1,128', '2024', '1,066', '2023', '946', '2022']
Row 201: ['Samoa', '1,024', '2024', '934', '2023', '857', '2022']
Row 202: ['São Tomé and Príncipe', '751', '2024', '603', '2023', '546', '2022']
Row 203: ['Dominica', '708', '2024', '654', '2023', '612', '2022']
Row 204: ['Tonga', '581', '2024', '500', '2022', '488', '2022']
Row 205: ['Micronesia', '484', '2024', '460', '2023', '427', '2022']
Row 206: ['Kiribati', '311', '2024', '279', '2023', '223', '2022']
Row 207: ['Palau', '308', '2024', '263', '2023', '225', '2022']
Row 208: ['Marshall Islands', '305', '2024', '284', '2023', '279', '2022']
Row 209: ['Nauru', '161', '2024', '154', '2023', '147', '2022']
Row 210: ['Tuvalu', '66', '2024', '62', '2023', '59', '2022']

In [217]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Base URL of the CoinMarketCap page
base_url = 'https://coinmarketcap.com/'

# List to store all data
all_data = []
columns = []

# Loop through pagination (1 to 5 pages as an example, adjust range as needed)
for page in range(1, 6):  # Adjust the range to scrape more pages
    # Construct the URL with the current page number
    url = f'{base_url}?page={page}'
    
    # Send a GET request to fetch the page content
    response = requests.get(url)
    
    # Parse the page content with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the table that contains the cryptocurrency data
    table = soup.find('table')
    
    # Find the table headers if it's the first page (to dynamically get the column names)
    if page == 1:
        header_row = table.find('thead').find_all('th')
        columns = [th.text.strip() for th in header_row]
    
    # Get all the rows from the table
    rows = table.find('tbody').find_all('tr')
    
    # Loop through rows to extract currency data
    for row in rows:
        data_row = [td.text.strip() for td in row.find_all('td')]
        if data_row:
            all_data.append(data_row)

# Create a DataFrame using the collected data and dynamic columns
df = pd.DataFrame(all_data, columns=columns)

# Display the DataFrame
print(df)

# Optionally, save the data to a CSV file
df.to_csv('coinmarketcap_all_data.csv')

        #             Name       Price   1h %  24h %   7d %  \
0       1       BitcoinBTC  $68,400.97  0.01%  0.40%  9.30%
1       2      EthereumETH   $2,648.15  0.00%  0.47%  7.59%
2       3       TetherUSDT     $0.9999  0.02%  0.01%  0.00%
3       4           BNBBNB     $596.66  0.04%  0.19%  4.08%
4       5        SolanaSOL     $158.90  0.00%  2.92%  8.23%
..  .. ..              ...         ...    ...    ...    ...
495                BENQIQI       $0.01          None   None
496             ArchLootAL       $0.13          None   None
497              BancorBNT       $0.52          None   None
498          EverscaleEVER       $0.03          None   None
499        Dolan DuckDOLAN       $0.66          None   None

                   Market Cap                         Volume(24h)  \
0    $1.35T$1,352,451,006,530          $13,667,351,998199,791 BTC
1    $318.86B$318,858,960,088         $8,053,888,1753,040,854 ETH
2    $120.15B$120,153,471,031  $31,940,990,11131,945,112,847 USDT
3      $86.92B$86,916,069,129         $1,451,391,9092,432,288 BNB
4      $74.67B$74,671,083,681        $1,744,192,46710,976,638 SOL
..                        ...                                 ...
495                      None                                None
496                      None                                None
497                      None                                None
498                      None                                None
499                      None                                None

       Circulating Supply Last 7 Days
0          19,770,306 BTC
1         120,389,492 ETH
2    120,168,979,664 USDT
3         145,656,657 BNB
4         469,923,763 SOL
..                    ...         ...
495                  None        None
496                  None        None
497                  None        None
498                  None        None
499                  None        None

[500 rows x 11 columns]

In [218]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL of the Etherscan Tokens page
url = "https://etherscan.io/tokens"

# Send a GET request to fetch the page content
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the page content with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table containing token data
    table = soup.find('table', {'class': 'table table-hover'})

    # Check if the table exists
    if table:
        # Extract table headers
        headers = [th.text.strip() for th in table.find_all('th')]

        # Extract table rows
        rows = []
        for tr in table.find_all('tr')[1:]:  # Skipping header row
            cells = [td.text.strip() for td in tr.find_all('td')]
            if cells:
                rows.append(cells)

        # Create a DataFrame using pandas
        df = pd.DataFrame(rows, columns=headers)

        # Display the DataFrame
        print(df)

        # Optionally save to CSV
        df.to_csv('etherscan_tokens.csv', index=False)
        print("Data saved to 'etherscan_tokens.csv'")
    else:
        print("Table not found on the page.")
else:
    print(f"Failed to retrieve page. Status code: {response.status_code}")

Failed to retrieve page. Status code: 403